### ISSUE TITLE
cannot obfuscate dist/public/index-nnnnn.js only.

### ISSUE THREAD

**Issue by Pleizz** [getkey/rollup-plugin-obfuscator#13]
obfuscator({ include: "" })]

obfuscate specific file only doesn't work.
include 'dist/public/index-nnn.js' only..
tried

'**/index-*.js'
'*/index*.js'
'public/index-*.js'
... etc

can i get some advices?

**Comment by getkey** [comment]
You have to exclude all other files, like so:

```js
obfuscator({
	include: 'index.js',
	exclude: '*',
})
```

Closing, reopen if that doesn't solve your issue.

**Comment by Pleizz** [comment]
`import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import obfuscator from "rollup-plugin-obfuscator";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
  },
  build: {
    assetsDir: "./public",
    rollupOptions: {
      output: {
        plugins: [
          obfuscator({
            include: "index.js",
            exclude: "*",
          }),
        ],
        manualChunks(id) {
          if (id.includes("node_modules")) {
            return "module_" + id.split("node_modules")[1].split("/")[1];
          }
        },
      },
    },
  },
});
`



build without obfuscate works fine.
but error occured from ant design with white empty screen.

![image](https://user-images.githubusercontent.com/87597383/212730615-cf17dacd-02f2-4359-ac46-c74eb751bbf0.png)

as a result, i wanna obfuscate only my code except node_modules file.

`obfuscator({
	include: 'index.js',
        exclude: '*'
})`

this didn't work for me.

![image](https://user-images.githubusercontent.com/87597383/212731028-0dd132fe-7262-42f6-a779-27c454214414.png)
this file must not be obfuscated.

can i get some advice?

thank you ^--^

p.s. under is list of files.

![image](https://user-images.githubusercontent.com/87597383/212731426-f0b0267d-5daf-403f-9447-7d60a7944403.png)

**Comment by Pleizz** [comment]
> You have to disable globalOptions, like so:
> 
> ```js
> obfuscator({
> 	globalOptions: false,
> 	include: 'index.js',
> })
> ```
> 
> Closing, reopen if that doesn't solve your issue.

Oh, i've tried your edited code.
but all of the file didn't obfuscated.
maybe include only dist/public/index-~~~~.js

tried: 

include
index-*.js
public/index-*.js
**/index-*.js

thank you

**Comment by getkey** [comment]
Oh, I thought you only wanted to obfuscate `index.js`, that's what https://github.com/getkey/rollup-plugin-obfuscator/issues/13#issuecomment-1384302215 does.

> i wanna obfuscate only my code except node_modules file

This is what the default of [exclude](https://github.com/getkey/rollup-plugin-obfuscator#exclude) and include does. So you just need to disable globalOptions.

```js
obfuscator({
	globalOptions: false,
})
```

**Comment by Pleizz** [comment]
> 

Exactly, i wanna obfuscate "src/app.tsx" file.
this file became "dist/public/index-aslkfj.js" after bundling.

which file should i try?

before bundling or after bundling..

before bundling: 'src/app.tsx'
after bundling: 'dist/public/index-randomStr.js'

thank you ^--^

**Comment by getkey** [comment]
rollup-plugin-obfuscator doesn't look at the filename after bundling, it looks at the filename before. So if you want to obfuscate **only** `src/app.tsx`, do `include: 'src/app.tsx'`. If you want to obfuscate all your code (but no node modules), the [default](https://github.com/getkey/rollup-plugin-obfuscator#include) needs no change.

But keep `globalOptions` to false. `globalOptions` runs a second pass after `fileOptions` on the entire bundle. This is not what you want here.

**Comment by Pleizz** [comment]
> rollup-plugin-obfuscator doesn't look at the filename after bundling, it looks at the filename before. So if you want to obfuscate **only** `src/app.tsx`, do `include: 'src/app.tsx'`. If you want to obfuscate all your code (but no node modules), the [default](https://github.com/getkey/rollup-plugin-obfuscator#include) needs no change.
> 
> But keep `globalOptions` to false. `globalOptions` runs a second pass after `fileOptions` on the entire bundle. This is not what you want here.

i've tried but didn't work T.T
so.. i edited static module..
this works..
thank you for helping me ^--^
happy new year and have a nice day :))

![image](https://user-images.githubusercontent.com/87597383/212936253-93053911-0f8e-4208-8482-64002f81651a.png)
