### ISSUE TITLE
Obfuscator breaks code when using import.meta.env

### ISSUE THREAD

**Issue by doroved** [getkey/rollup-plugin-obfuscator#15]
**Describe the bug**

- [?] to the best of my knowledge, this is a bug in `rollup-plugin-obfuscator` and not in `javascript-obfuscator`

Hi, thanks for the update!
I encountered an error that appears when using ENV.
How can it be resolved?

```JS
import ky from 'ky'

const api = ky.create({
  prefixUrl: import.meta.env.VITE_APP_API,
  headers: {
    Authorization: localStorage.authToken || '',
  },
})
```

<img width="493" alt="image" src="https://user-images.githubusercontent.com/30116541/218221944-c6a26138-86d8-4de7-9404-641745f21813.png">

**Stack trace**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'VITE_APP_API')
```

**Package versions:**
- `rollup-plugin-obfuscator`: v1.0.1
- `javascript-obfuscator`: v4.0.0
- `vite`: v3.2.4

**Comment by getkey** [comment]
This is basically the same problem as #11. I described a solution in this comment https://github.com/getkey/rollup-plugin-obfuscator/issues/11#issuecomment-1426468581 (there might be other solutions, if so let me know).

Reopen if that doesn't fix it for you!

**Comment by doroved** [comment]
Thank you. It all worked out.
I have one more question, I want the obfuscation code to look like this
<img width="501" alt="image" src="https://user-images.githubusercontent.com/30116541/218223969-f9c166a1-d1b2-400e-be6f-e0b5dbd5891f.png">

But your plugin obfuscates like this
<img width="417" alt="image" src="https://user-images.githubusercontent.com/30116541/218224232-1341ae2f-d645-4dbc-a396-bc835a5106ec.png">

I would like to have the first example of how to do this?
I am using the default options.
In the first example plugin: vite-plugin-obfuscator

**Comment by huhai122** [comment]
> 谢谢。一切都解决了。 我还有一个问题，我希望混淆代码看起来像这样 <img alt="图像" width="501" src="https://user-images.githubusercontent.com/30116541/218223969-f9c166a1-d1b2-400e-be6f-e0b5dbd5891f.png">
> 
> 但是你的插件会像这样混淆 <img alt="图像" width="417" src="https://user-images.githubusercontent.com/30116541/218224232-1341ae2f-d645-4dbc-a396-bc835a5106ec.png">
> 
> 我想看第一个示例，说明如何执行此操作？ 我使用的是默认选项。 第一个示例中的插件：vite-plugin-obfuscator

how do you fix that?
