### ISSUE TITLE
Why is the obfuscation method different from the default settings of another plugin that uses javascript-obfuscator

### ISSUE THREAD

**Issue by doroved** [getkey/rollup-plugin-obfuscator#16]
Thank you. It all worked out.
I have one more question, I want the obfuscation code to look like this
<img width="501" alt="image" src="https://user-images.githubusercontent.com/30116541/218223969-f9c166a1-d1b2-400e-be6f-e0b5dbd5891f.png">

But your plugin obfuscates like this
<img width="417" alt="image" src="https://user-images.githubusercontent.com/30116541/218224232-1341ae2f-d645-4dbc-a396-bc835a5106ec.png">

I would like to have the first example of how to do this?
I am using the default options.
In the first example plugin: vite-plugin-obfuscator

_Originally posted by @doroved in https://github.com/getkey/rollup-plugin-obfuscator/issues/15#issuecomment-1426511880_

**Comment by getkey** [comment]
When you remove the plugin from your config, what do you get?

**Comment by doroved** [comment]
> When you remove the plugin from your config, what do you get?

This is what the code looks like after building Vite without your plugin
<img width="373" alt="image" src="https://user-images.githubusercontent.com/30116541/218225321-0fe4d9ef-737b-4b5b-a4c1-d34aced76fb9.png">

This is what the code looks like with your plugin. The obfuscation seems to be there, but it doesn't look like what you get with the default config of javascript-obfuscator itself
![image](https://user-images.githubusercontent.com/30116541/218225410-828f8a76-b97d-4923-b60a-09cbd48760e3.png)

**Comment by getkey** [comment]
I'm pretty sure this is the result of rollup-plugin-obfuscator running before minification. Could you disable [minification](https://vitejs.dev/config/build-options.html#build-minify) to test that theory?

It's [not possible](https://vitejs.dev/guide/api-plugin.html#plugin-ordering) to make rollup-plugin-obfuscator run after minification, even with `enforce: 'post'`.
The only way to prevent that would be disabling minification. But I would not recommend it: obfuscation that can be removed so easily is useless, so might as well have lean minified JS. 😉

**Comment by doroved** [comment]
> I'm pretty sure this is the result of rollup-plugin-obfuscator running before minification. Could you disable [minification](https://vitejs.dev/config/build-options.html#build-minify) to test that theory?
> 
> It's [not possible](https://vitejs.dev/guide/api-plugin.html#plugin-ordering) to make rollup-plugin-obfuscator run after minification, even with `enforce: 'post'`. The only way to prevent that would be disabling minification. But I would not recommend it: obfuscation that can be removed so easily is useless, so might as well have lean minified JS. 😉

Yes, with minify:false it will obfuscate properly
<img width="648" alt="image" src="https://user-images.githubusercontent.com/30116541/218275014-9d4f90fa-19a4-4a1d-87d0-999344bf3e39.png">

Why then does the vite-plugin-obfuscator plugin work correctly and the obfuscated code is minified? But it obfuscates all code, including library code, which is unnecessary.
So your plugin does not work with Vite? That's too bad.

**Comment by doroved** [comment]
This is how **[vite-plugin-obfuscator](https://www.npmjs.com/package/vite-plugin-obfuscator)** works.
It works, why don't you?)
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/30116541/218275373-69fd5600-07d0-437d-a769-cb0869dc8a9e.png">

**Comment by getkey** [comment]
I tried, but I haven't been able to make vite-plugin-obfuscator work. Please make a repo with a minimal reproduction case and send me the link so I can look how it works.

**Comment by doroved** [comment]
> I tried, but I haven't been able to make vite-plugin-obfuscator work. Please make a repo with a minimal reproduction case and send me the link so I can look how it works.

Use this config and everything should work fine.
This plugin unfortunately obfuscates all code, including libraries, and I need only the project code.

**vite.config.js**
```JS
import { fileURLToPath, URL } from 'node:url'
import { viteObfuscateFile } from 'vite-plugin-obfuscator'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue(), viteObfuscateFile()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})
```
If it does not work now, I will prepare a repository.

**Comment by getkey** [comment]
Thanks, I was able to reproduce and have a deeper look at what that plugin is doing. It is modifying the bundle during the HTML transform phase, which apparently happens after the minification. Unfortunately this technique does not allow excluding libraries from the bundle.

Now the question is, should rollup-plugin-obfuscator adopt this technique when `global` is set to `true`?

1. as I explained in [this comment](https://github.com/getkey/rollup-plugin-obfuscator/issues/16#issuecomment-1426844763), I think this isn't a desirable use-case: if all it takes to turn [fully-obfuscated code](https://github.com/getkey/rollup-plugin-obfuscator/issues/16#issuecomment-1426849626) into the semi-obfuscated code from [the second image here](https://github.com/getkey/rollup-plugin-obfuscator/issues/16#issue-1580515001) is to run terser on it, the former provides no additional protection. In which case you're better off not shipping that dead weight to your users
2. there is an alternative way to achieve that outcome, by [disabling minification](https://vitejs.dev/config/build-options.html#build-minify) (and optionally running @rollup/plugin-terser before rollup-plugin-obfuscator). Which, by the way, will work with `global: false`
3. the Vite API to modify the bundle during the [HTML transform phase](https://vitejs.dev/guide/api-plugin.html#transformindexhtml) is undocumented

So for all these reasons, I think it would make for a bad addition.

If you want to do it anyway, here is the alternative way to do it I was talking about in 2. (it will exclude library code):

```ts
// vite.config.js

import { defineConfig } from 'vite';
import obfuscator from 'rollup-plugin-obfuscator';
import terser from '@rollup/plugin-terser';

export default defineConfig({
	build: {
		minify: false,
	},
	plugins: [
		terser(),
		obfuscator(),
	],
});
```
