### ISSUE TITLE
vite-plugin-obfuscator

### ISSUE THREAD

**Issue by ibilux** [getkey/rollup-plugin-obfuscator#4]
Vite plugins are an extension of Rollup's plugin interface.
However, it would be better if you can make another repository for Vite.

Regards,

**Comment by getkey** [comment]
> If the plugin doesn't use Vite specific hooks and can be implemented as a Compatible Rollup Plugin, then it is recommended to use the Rollup Plugin naming conventions

https://vitejs.dev/guide/api-plugin.html

This plugin doesn't need to use Vite hooks. If you think it can be improved by supporting Vite, please open a PR/issue. Until then, there is no reason to change the name.
